Implement eris.type() to look up types from libraries
This patch adds a new function to the module, eris.type(), which receives a
library and a type name, and looks it up the type. This allows for more easily
instantiating values. For example:

  lib = eris.load("libfoo")
  int32_t = eris.type(lib, "int32_t")
  intarray = int32_t(10)
  intarray[5] = 32

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -249,6 +249,24 @@ then
 	die 'Could not find libdwarf'
 fi
 
+if ! try_link 'dwarf_pubtype_die_offset()' -ldwarf -lelf <<-EOF
+	#include <libdwarf/libdwarf.h>
+	int main () { return dwarf_pubtype_die_offset (0, 0, 0); }
+	EOF
+then
+	if try_link 'dwarf_pubtype_type_die_offset()' -ldwarf -lelf <<-EOF
+	#define dwarf_pubtype_die_offset dwarf_pubtype_type_die_offset
+	#include <libdwarf/libdwarf.h>
+	int main () { return dwarf_pubtype_die_offset (0, 0, 0); }
+	EOF
+	then
+		# Nasty, nasty libdwarf
+		CPPFLAGS="${CPPFLAGS} -DERIS_WORKAROUND_DWARF_PUBTYPE_DIE_OFFSET=1"
+	else
+		die 'Could not find libdwarf'
+	fi
+fi
+
 if try_link 'dlopen()' -ldl <<-EOF
 	#include <dlfcn.h>
 	int main () { return dlopen ((void*) 0, 0) != (void*) 0; }
