run-tests: Check that build outputs are present
Also, hint to the user that it may be needed to run Ninja (or Make) to
ensure that the build is completed before running the test suite.

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -21,5 +21,14 @@ objdir=$(sed -e 's/^obj[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' -e 'd' build.conf)
 cd "${objdir}"
 objdir=$(pwd)
 
+for file in eris libtest.so eris.so testutil.so
+do
+	if ! [ -r "${file}" ] ; then
+		echo "File not found: ${objdir}/${file}" 1>&2
+		echo "Have you run 'ninja' or 'make'?" 1>&2
+		exit 1
+	fi
+done
+
 export LUA_INIT="@${erisdir}/assertions.lua"
 exec "./eris" "${erisdir}/harness.lua" "${erisdir}" "${curdir}" "$@"
